### ISSUE TITLE
[Bug] Crazzy bat 🦇💫

### ISSUE THREAD

**Issue by N4TH4NOT** [MrMicky-FR/InfiniteJump#1]
I found a pretty funny bug today :
When I leave my server when I flying (creative) and rejoin my server in survival (force game mode survival on join 😉), I fly and I can't walk : when I try it, InfiniteJump is triggered so I jump (like the name of plugin 😆 ) as infinite 😋 
It's funny but if you can fix it anyway that will be nice 👌 
I enjoy yours plugins 😄

**Comment by MrMicky-FR** [comment]
Thanks 😄 

It's not really a bug, when you join and if you have the permission `infinitejump.use` you will have double/triple/infinite jump (depends on your permissions)

**Comment by MrMicky-FR** [comment]
Finally I found this bug and I fixed it in 55189c4c15b5ebb673c2f87217211779bcde67be and now you have an option to don't enable the jump when you join
