### ISSUE TITLE
Add /ijump Enable/Disable Commands

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [MrMicky-FR/InfiniteJump#12]
Could you please add the commands:
/ijump enable (player)
/ijump disable (player)

(player) = optional. If not specified it is the player running the command.

The toggle command is great when it is used directly by players. However, the commands above are more useful when a server owner wishes to run it via a plugin. For instance, when a player enters a WorldGuard region I'd like to disable iJump for the player. If I used the toggle command then if the player had it off and entered the claim it would turn it on which isn't what I want.

Please add this feature. Thank you!

**Comment by MrMicky-FR** [comment]
Hi, added `/ijump [enable|disable] [player]` as `/ijump toggle [on|off] [player]`. To toggle for others players, the permission  `infinitejump.toggle.others` is required.

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> Hi, added `/ijump [enable|disable] [player]` as `/ijump toggle [on|off] [player]`. To toggle for others players, the permission `infinitejump.toggle.others` is required.

Great! Thank you! <3
