### ISSUE TITLE
EnableOnJoin doesnt seem to work

### ISSUE THREAD

**Issue by Vynxly** [MrMicky-FR/InfiniteJump#3]
Whenever players enter the server, they have to disable and re-enable it for it to kick in.

Spigot 1.14.4

**Comment by MrMicky-FR** [comment]
Hello,

Make sure the players have the permission `infinitejump.use` when they join

**Comment by Vynxly** [comment]
Yeah, made sure of that, still happens unfortunately. Could it be because I've made it a donator permission instead of a default one?

It also seems you're able to run with 3 or lower hunger when you have it toggled, not sure why. My players seem to enjoy that though and I as well, but I don't imagine that was intended?
