### ISSUE TITLE
NoCheatPlus stops detecting cheats when Infinite Jump toggle is on.

### ISSUE THREAD

**Issue by c0if** [MrMicky-FR/InfiniteJump#6]
A few days ago, I noticed that when I had Infinite Jump toggled and started using cheats, NoCheatPlus would not prevent the cheat or ban the user. NoCheatPlus starts to detect cheats when Infinite Jump is off.

I am running a Custom Spigot Build running 1.8.8 (not the issue even used PaperSpigot 1.8.8)

**Comment by MrMicky-FR** [comment]
It should just disable fly detection for users with infinite jump enabled to prevent false detections

**Comment by c0if** [comment]
> It should just disable fly detection for users with infinite jump enabled to prevent false detections

Yeah, that's what I meant, I only remember having fly on with it toggled and allowed to me fly anywhere without any alerts.

**Comment by MrMicky-FR** [comment]
Currently I don’t have a better solution because removing the NPC hook will create false detections when players use jump
