### ISSUE TITLE
Ops always get infinite jump even without permissions or with negated permissions

### ISSUE THREAD

**Issue by oskarkk** [MrMicky-FR/InfiniteJump#8]
If you're op, you'll always be able to jump to infinity if you have `infinitejump.use` permission. Permissions `infinitejump.3`, `infinitejump.4` and `infinitejump.infinite` aren't needed and negating them doesn't help.

**Comment by NatsumeLS** [comment]
Op is a wildcards permission and basically not part of bukkit permission. So technically you shouldn't be able to negates it.

Its also not a good practice to use wildcards permission in a server.
So I recommend not to use it and by doing so would also solve your issue.

**Comment by MrMicky-FR** [comment]
You need to also negate from `infinitejump.2` to `infinitejump.10`, if you use LuckPerms you can directly negate `infinitejump.{2-10}`

**Comment by oskarkk** [comment]
@MrMicky-FR Thanks, it works. With:

```
    - -infinitejump.3
    - -infinitejump.4
    - -infinitejump.5
    - -infinitejump.6
    - -infinitejump.7
    - -infinitejump.8
    - -infinitejump.9
    - -infinitejump.10
    - -infinitejump.infinite
```

... I was able to restrict ops to only double jump. It should be described on the plugin page, right now only infinitejump.3 and 4 are listed.

**Comment by MrMicky-FR** [comment]
I've upadted the plugin page to include this
