### ISSUE TITLE
Can't change the sounds

### ISSUE THREAD

**Issue by JustWavey** [MrMicky-FR/InfiniteJump#9]
I have a server on paper 1.8.8 and for some reason, I can't change the sound. I can change the pitch, the volume, but the actual sound effect stays the same as ENTITY_BAT_TAKEOFF. (I tried changing it into a TNT sound effect with RANDOM_EXPLODE and ENTITY_GENERIC_EXPLODE)

**Comment by MrMicky-FR** [comment]
You can find the 1.8 sounds here: https://minuskube.fr/javadocs/spigot/1.8.8/org/bukkit/Sound.html

**Comment by JustWavey** [comment]
Thanks, its been working after that
